#include <gpiod.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>

// Type IEC_BOOL conforme a MatIEC
typedef uint8_t IEC_BOOL;
typedef uint16_t IEC_UINT;

// IEC_STRING structure matching iec_std_lib.h
typedef struct {
    uint8_t len;
    uint8_t body[32]; // Standard ST string buffer
} IEC_STRING;

// Link directly to external OpenPLC variables instantiated by glueVars.cpp
#ifdef __cplusplus
extern "C" {
#endif

// Notice the double underscores generated by glueVars macro: __##name -> ____MD0
extern IEC_STRING ____MD0; 

// Pointers for Digital Inputs/Outputs generated by glueVars.cpp: [BYTE][BIT]
extern IEC_BOOL *bool_input[1024][8];
extern IEC_BOOL *bool_output[1024][8];

// Pointers for Analog 16-bit Word Outputs (%QW0, %QW1 intended for PWM outputs
extern IEC_UINT *int_output[1024];

#ifdef __cplusplus
}
#endif

// -----------------------------------------------------------------------------
// PWM DEFINITIONS (TIM3 = pwmchip0/pwm1, TIM5 = pwmchip4/pwm0)
// -----------------------------------------------------------------------------
#define PWM1_EXPORT    "/sys/class/pwm/pwmchip0/export"
#define PWM1_PERIOD    "/sys/class/pwm/pwmchip0/pwm1/period"
#define PWM1_DUTY      "/sys/class/pwm/pwmchip0/pwm1/duty_cycle"
#define PWM1_ENABLE    "/sys/class/pwm/pwmchip0/pwm1/enable"

#define PWM2_EXPORT    "/sys/class/pwm/pwmchip4/export"
#define PWM2_PERIOD    "/sys/class/pwm/pwmchip4/pwm0/period"
#define PWM2_DUTY      "/sys/class/pwm/pwmchip4/pwm0/duty_cycle"
#define PWM2_ENABLE    "/sys/class/pwm/pwmchip4/pwm0/enable"

#define BASE_PERIOD_NS 1000000 // 1 kHz base frequency (1,000,000 ns)

static int duty1_fd = -1;
static int duty2_fd = -1;

struct GPIOPin {
    const char* chip_name;
    unsigned int line_num;
    struct gpiod_line* line_handle;
};

// Cartographie des sorties structurée en [OCTET][BIT] (2 octets de 8 bits)
static struct GPIOPin out_pins[2][8] = {
    // Octet 0 (%QX0.0 a %QX0.7)
    {
        {"gpiochip5", 0,  NULL}, // %QX0.0 - OUT0 (PF0  / CN2 Pin 18)
        {"gpiochip5", 9,  NULL}, // %QX0.1 - OUT1 (PF9  / CN2 Pin 19)
        {"gpiochip5", 8,  NULL}, // %QX0.2 - OUT2 (PF8  / CN2 Pin 21)
        {"gpiochip5", 4,  NULL}, // %QX0.3 - OUT3 (PF4  / CN2 Pin 22)
        {"gpiochip5", 7,  NULL}, // %QX0.4 - OUT4 (PF7  / CN2 Pin 23)
        {"gpiochip5", 6,  NULL}, // %QX0.5 - OUT5 (PF6  / CN2 Pin 24)
        {"gpiochip5", 3,  NULL}, // %QX0.6 - OUT6 (PF3  / CN2 Pin 26)
        {"gpiochip5", 15, NULL}  // %QX0.7 - OUT7 (PF15 / CN2 Pin 27)
    },
    // Octet 1 (%QX1.0 a %QX1.7)
    {
        {"gpiochip0", 13, NULL}, // %QX1.0 - RED LED (PA13)
        {"gpiochip7", 7,  NULL}, // %QX1.1 - ORANGE LED (PH7)
        {NULL, 0, NULL},         // %QX1.2 - Non attribue
        {NULL, 0, NULL},         // %QX1.3 - Non attribue
        {NULL, 0, NULL},         // %QX1.4 - Non attribue
        {NULL, 0, NULL},         // %QX1.5 - Non attribue
        {NULL, 0, NULL},         // %QX1.6 - Non attribue
        {NULL, 0, NULL}          // %QX1.7 - Non attribue
    }
};

// ENTRÉES (%IX0.0 a %IX0.7)
static struct GPIOPin in_pins[8] = {
    {"gpiochip0", 8,  NULL}, // %IX0.0 - IN0 (PA8  / CN2 Pin 7)
    {"gpiochip1", 10, NULL}, // %IX0.1 - IN1 (PB10 / CN2 Pin 8)
    {"gpiochip1", 12, NULL}, // %IX0.2 - IN2 (PB12 / CN2 Pin 10)
    {"gpiochip6", 8,  NULL}, // %IX0.3 - IN3 (PG8  / CN2 Pin 11)
    {"gpiochip8", 5,  NULL}, // %IX0.4 - IN4 (PI5  / CN2 Pin 12)
    {"gpiochip3", 7,  NULL}, // %IX0.5 - IN5 (PD7  / CN2 Pin 13)
    {"gpiochip6", 15, NULL}, // %IX0.6 - IN6 (PG15 / CN2 Pin 15)
    {"gpiochip5", 1,  NULL}  // %IX0.7 - IN7 (PF1  / CN2 Pin 16)
};

static struct gpiod_chip* open_out_chips[2][8] = { {NULL} };
static struct gpiod_chip* open_in_chips[8]     = {NULL};

void write_log(const char *text) {
    FILE *f = fopen("/tmp/openplc_gpio.log", "a");
    if (f) {
        fputs(text, f);
        fclose(f);
    }
}

static char previous_lcd_text[32] = "";
static bool LCDlit = false; // Whatever if it is lit or not, we light it once at start

static void write_to_lcd_device(const char *text, uint8_t length)
{
    int lcd_fd = open("/dev/lcd", O_WRONLY);
    if (lcd_fd >= 0) {
	//First erase both lcd lines
        write(lcd_fd, "\x1b[2J", 4);
        write(lcd_fd, text, length);
        close(lcd_fd);
    }
}

static void write_sysfs(const char *path, const char *value) {
    int fd = open(path, O_WRONLY);
    if (fd >= 0) {
        write(fd, value, strlen(value));
        close(fd);
    }
}

static void init_pwm_channel(const char* export_path, const char* period_path, const char* duty_path, const char* enable_path, const char* channel_id, int* out_fd) {
    // Export channel
    write_sysfs(export_path, channel_id);
    usleep(100000); // Wait for sysfs node creation

    // Set 1kHz period and default 0 duty cycle
    char period_str[16];
    snprintf(period_str, sizeof(period_str), "%d", BASE_PERIOD_NS);
    write_sysfs(period_path, period_str);
    write_sysfs(duty_path, "0");
    write_sysfs(enable_path, "1");

    *out_fd = open(duty_path, O_WRONLY);
    if (*out_fd < 0) {
        char buf[128];
        snprintf(buf, sizeof(buf), "ERROR: Impossible d'ouvrir le sysfs duty cycle (%s)\n", duty_path);
        write_log(buf);
    } else {
        char buf[128];
        snprintf(buf, sizeof(buf), "SUCCESS: PWM Initialise (%s)\n", duty_path);
        write_log(buf);
    }
}

void initializeHardware()
{
    write_log("\n=========================================\n");
    write_log("  STM32MP1 HARDWARE INITIALIZATION       \n");
    write_log("=========================================\n");

    // Loop over outputs GPIO (from %QX0.0 to %QX1.7)
    for (int byte = 0; byte <= 1; byte++) {
        for (int bit = 0; bit < 8; bit++) {
            //Ignore none attributed pins
            if (out_pins[byte][bit].chip_name == NULL) {
                continue;
            }

            open_out_chips[byte][bit] = gpiod_chip_open_by_name(out_pins[byte][bit].chip_name);
            if (!open_out_chips[byte][bit]) {
                char buf[128];
                snprintf(buf, sizeof(buf), "ERROR: Impossible d'ouvrir %s pour %%QX%d.%d\n", out_pins[byte][bit].chip_name, byte, bit);
                write_log(buf);
                continue;
            }

            out_pins[byte][bit].line_handle = gpiod_chip_get_line(open_out_chips[byte][bit], out_pins[byte][bit].line_num);
            if (!out_pins[byte][bit].line_handle) {
                char buf[128];
                snprintf(buf, sizeof(buf), "ERROR: Impossible d'obtenir la ligne %u (%s)\n", out_pins[byte][bit].line_num, out_pins[byte][bit].chip_name);
                write_log(buf);
                continue;
            }

            int ret = gpiod_line_request_output(out_pins[byte][bit].line_handle, "openplc_qx", 0);
            if (ret < 0) {
                char buf[128];
                snprintf(buf, sizeof(buf), "ERROR: Broche busy ou indisponible pour %%QX%d.%d\n", byte, bit);
                out_pins[byte][bit].line_handle = NULL;
                write_log(buf);
            } else {
                char buf[128];
                snprintf(buf, sizeof(buf), "SUCCESS: Sortie %%QX%d.%d (%s line %u)\n", byte, bit, out_pins[byte][bit].chip_name, out_pins[byte][bit].line_num);
                write_log(buf);
            }
        }
    }

    // Initialise inputs (from %IX0.0 to %IX0.7)
    for (int i = 0; i < 8; i++) {
        if (in_pins[i].chip_name == NULL) continue;

        open_in_chips[i] = gpiod_chip_open_by_name(in_pins[i].chip_name);
        if (!open_in_chips[i]) continue;

        in_pins[i].line_handle = gpiod_chip_get_line(open_in_chips[i], in_pins[i].line_num);
        if (!in_pins[i].line_handle) continue;

        int ret = gpiod_line_request_input(in_pins[i].line_handle, "openplc_ix");
        if (ret < 0) {
            char buf[128];
            snprintf(buf, sizeof(buf), "ERROR: Broche busy ou indisponible pour %%IX0.%d\n", i);
            in_pins[i].line_handle = NULL;
            write_log(buf);
        } else {
            char buf[128];
            snprintf(buf, sizeof(buf), "SUCCESS: Entree %%IX0.%d (%s line %u)\n", i, in_pins[i].chip_name, in_pins[i].line_num);
            write_log(buf);
        }
    }

    // Initialise PWM1 (TIM3_CH2 -PC7 pin 33- on pwmchip0/pwm1) -> Controlled by %QW0
    init_pwm_channel(PWM1_EXPORT, PWM1_PERIOD, PWM1_DUTY, PWM1_ENABLE, "1", &duty1_fd);

    // Initialise PWM2 (TIM5_CH1 -PH11 pin 31- on pwmchip4/pwm0) -> Controlled by %QW1
    init_pwm_channel(PWM2_EXPORT, PWM2_PERIOD, PWM2_DUTY, PWM2_ENABLE, "0", &duty2_fd);
}

void updateBuffersIn()
{
    if (bool_input == NULL || bool_input[0] == NULL) return;

    for (int i = 0; i < 8; i++) {
        if (in_pins[i].line_handle != NULL && bool_input[0][i] != NULL) {
            int val = gpiod_line_get_value(in_pins[i].line_handle);
            if (val >= 0) {
                *bool_input[0][i] = !(IEC_BOOL)val; //ACTIVE_LOW in dt but have to NOT line_get_value.
            }
        }
    }
}

void updateBuffersOut()
{
    if (bool_output != NULL) {
        // 1. Process GPIO Outputs (%QX0.0 - %QX1.7)
        for (int byte = 0; byte <= 1; byte++) {
            if (bool_output[byte] == NULL) continue;

            for (int bit = 0; bit < 8; bit++) {
                if (out_pins[byte][bit].line_handle != NULL && bool_output[byte][bit] != NULL) {
                    int val = (*bool_output[byte][bit]) ? 1 : 0;
                    gpiod_line_set_value(out_pins[byte][bit].line_handle, val);
                }
            }
        }
    }

    // 2. Process PWM Outputs (%QW0 & %QW1)
    if (int_output != NULL) {
        char buf[16];
        int len;

        // %QW0 -> PWM 1
        if (int_output[0] != NULL && duty1_fd >= 0) {
            uint16_t plc_val0 = *int_output[0];
            uint32_t duty_ns0 = ((uint32_t)plc_val0 * BASE_PERIOD_NS) / 65535;
            len = snprintf(buf, sizeof(buf), "%u", duty_ns0);
            pwrite(duty1_fd, buf, len, 0);
        }

        // %QW1 -> PWM 2
        if (int_output[1] != NULL && duty2_fd >= 0) {
            uint16_t plc_val1 = *int_output[1];
            uint32_t duty_ns1 = ((uint32_t)plc_val1 * BASE_PERIOD_NS) / 65535;
            len = snprintf(buf, sizeof(buf), "%u", duty_ns1);
            pwrite(duty2_fd, buf, len, 0);
        }
    }

    // 3. Read the IEC_STRING from %MD0 (____MD0 in glueVars.cpp)
    char current_text[32] = {0};
    uint8_t len = ____MD0.len;
    if (len > 31) len = 31; // Safety bounds check

    memcpy(current_text, ____MD0.body, len);
    current_text[len] = '\0';

    //Light first time only
    if (LCDlit == false) {
        char lightstring[]= "\x1b[L+\n";
        write_to_lcd_device(lightstring, strlen(lightstring));
        LCDlit = true;
    }

    // Only write to character device if text has changed
    if (strcmp(current_text, previous_lcd_text) != 0) {
        char buf[128];
        write_to_lcd_device(current_text, len);
        strncpy(previous_lcd_text, current_text, sizeof(previous_lcd_text));
        snprintf(buf, sizeof(buf), "LCD: Text changed [%s] len[%d]\n",____MD0.body,____MD0.len); //Debug
        write_log(buf);
    }
}

void finalizeHardware()
{
    write_log("Finalize Hardware: Free PWM and GPIO lines...\n");

    // Safely shutdown PWM channels
    if (duty1_fd >= 0) {
        pwrite(duty1_fd, "0", 1, 0);
        close(duty1_fd);
        duty1_fd = -1;
    }
    write_sysfs(PWM1_ENABLE, "0");

    if (duty2_fd >= 0) {
        pwrite(duty2_fd, "0", 1, 0);
        close(duty2_fd);
        duty2_fd = -1;
    }
    write_sysfs(PWM2_ENABLE, "0");

    // Close GPIO lines
    for (int byte = 0; byte <= 1; byte++) {
        for (int bit = 0; bit < 8; bit++) {
            if (out_pins[byte][bit].line_handle) {
                gpiod_line_release(out_pins[byte][bit].line_handle);
                out_pins[byte][bit].line_handle = NULL;
            }
            if (open_out_chips[byte][bit]) {
                gpiod_chip_close(open_out_chips[byte][bit]);
                open_out_chips[byte][bit] = NULL;
            }
        }
    }

    for (int i = 0; i < 8; i++) {
        if (in_pins[i].line_handle) {
            gpiod_line_release(in_pins[i].line_handle);
            in_pins[i].line_handle = NULL;
        }
        if (open_in_chips[i]) {
            gpiod_chip_close(open_in_chips[i]);
            open_in_chips[i] = NULL;
        }
    }
}

