#!/bin/sh
# Copyright (C) 2011 O.S. Systems Software LTDA.
# Licensed on MIT

finish_enabled() {
	return 0
}

finish_run() {
	if [ -n "$ROOTFS_DIR" ]; then
		if [ ! -d $ROOTFS_DIR/dev ]; then
			fatal "ERROR: There's no '/dev' on rootfs."
		fi

		info "Switching root to '$ROOTFS_DIR'..."

		debug "Moving /dev, /proc and /sys onto rootfs..."
		mount --move /dev $ROOTFS_DIR/dev
		mount --move /proc $ROOTFS_DIR/proc
		mount --move /sys $ROOTFS_DIR/sys

		echo "Do you want to switch_root ? y/n [5sec y=default]" > /dev/console
		read -t 4 answer
		if [ "$answer" = "n" ]; then
			echo "You entered [$answer] No switch_root => only /bin/sh" > /dev/console
			exec sh
		else
			cd $ROOTFS_DIR
			echo "We switch_root. ROOTFS_DIR=$ROOTFS_DIR, bootparam_init=$bootparam_init"
			exec switch_root -c /dev/console $ROOTFS_DIR ${bootparam_init:-/sbin/init}
		fi
	else
		debug "No rootfs has been set"
	fi
}
